### ISSUE TITLE
The farm

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#350] opened 2023-10-19 20:39 UTC
### Description

Tractor trailers fall to the ground.

### Expected behaviour

Stay on the ground.

### Reproduction steps

```bash
1. Buy a trailer
2. It becomes transparent and falls under the ground
```

**Comment by hugoheml** [comment] 2024-06-30 15:52
Should be resolved by a new check in the GProtect addon (the issue is normaly mentionned - sv_ghosting.lua)

**Closed** 2024-06-30 15:52 UTC
Labels: bug, Important
