### ISSUE TITLE
Robbery house equipment

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#167] opened 2023-06-05 21:08 UTC
### Description

At the end of the robbery, we get the MAC 11 gun back
And when the fire department resuscitates us, we get the MAC 11 gun and the access card back.

### Expected behaviour

Non-refundable equipment.

### Reproduction steps

```bash
.
```

**Comment by hugoheml** [comment] 2024-06-30 20:44
I close the issue, if the problem is not solved you can reopen it.

**Closed** 2024-06-30 20:44 UTC
Labels: bug, need test
